---
abstract: 'make NEXT suck less'
author:
  - 'Florian Ragwitz C<rafl@debian.org>'
build_requires:
  Test::Exception: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-C3-Adopt-NEXT
no_index:
  directory:
    - inc
    - t
requires:
  MRO::Compat: 0
  NEXT: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
